---
name: "Auto Organize"
guid: "70b7b43b-471b-4159-b4be-56750c795499"
version: "7.0.0.0"
jellyfin_version: "10.5.0.0"
owner: "jellyfin"
overview: "Automatically organize your media"
description: "Automatically organize your media"
category: "General"
artifacts:
- "Emby.AutoOrganize.dll"
changelog: >
  changelog
